name: CI/CD Pipelines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Validate Installation
        run: |
          echo "Validating installation..."
          command -v git
          command -v docker
          command -v docker-compose
          command -v mvn

  build:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: ./mvnw -B package

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify JAR file
        run: |
          echo "Verifying JAR file presence..."
          ls -al /home/project/spring-petclinic/target/
          if [ -z "$(find /home/project/spring-petclinic/target/ -name 'spring-petclinic-3.3.0-SNAPSHOT.jar')" ]; then
            echo "JAR file not found in target directory!"
            exit 1
          fi

      - name: Free up port 8080
        run: |
          echo "Freeing up port 8080..."
          if sudo lsof -i:8080; then
            sudo lsof -t -i:8080 | xargs sudo kill -9
          fi

      - name: Add SSH host key
        env:
          DEPLOY_SERVER: '103.151.111.46'
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

      - name: Deploy application
        env:
          DEPLOY_SERVER: '103.151.111.46'
          DEPLOY_PORT: '8080'
          DEPLOY_USER: 'project'
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Deploying application to $DEPLOY_SERVER"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          scp -i ~/.ssh/id_rsa /home/project/spring-petclinic/target/spring-petclinic-3.3.0-SNAPSHOT.jar $DEPLOY_USER@$DEPLOY_SERVER:/home/project/spring-petclinic/
          ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_SERVER "java -jar /home/project/spring-petclinic/spring-petclinic-3.3.0-SNAPSHOT.jar"

  test:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check application URL
        run: |
          echo "Checking application URL"
          curl -s http://103.151.111.46:8080 || exit 1

      - name: Run tests
        run: ./mvnw test
